### ISSUE TITLE
Make it easier to compare sceenshots

### ISSUE THREAD

**Issue by rparrett** [TheBevyFlock/bevy-example-runner#1]
Right now it's really difficult to figure out what might have changed between two screenshots at a glance, because:

- The thumbnails are small and compressed
- When hovering over one and moving to hover over another, the first screenshot goes away and the second reappears in a slightly different spot
- There is no way to download or open the screenshots in a new browser window except by manual excavation in browser dev tools
- (Maybe should be tracked in a separate issue), but the popover is mostly hidden off-screen for examples near the bottom of the page

Are full-size / losslessly compressed screenshots even made available by Percy? Or is a "diff image" available?

**Comment by mockersf** [comment]
It's a bit hidden, and could be made more accessible... in the "about" page, there are links to the Percy project. after a few clicks you should have this view: https://percy.io/dede4209/Screenshots-Linux-Vulkan/builds/30653228/changed/1692973656?browser=chrome&browser_ids=48&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=1280

**Comment by rparrett** [comment]
Ah, okay. That's great. So maybe we could link to the specific build in Percy in the table header or something?

**Comment by mockersf** [comment]
I think it should be possible to make the icon in the row/column a link to the actual comparison screen. All the ids should be available

**Comment by rparrett** [comment]
I wouldn't mind working on this.

It seems like you need the percy project (e.g. `dede4209/Screenshots-Windows-DX12`) to construct a link to a particular build. This doesn't seem to be available in the data that's currently being retrieved by the percy API and stored.

Do you have any opinions about how that value should make its journey into the template?

**Comment by mockersf** [comment]
you could extract it from the same field where we get the build id: https://github.com/TheBevyFlock/bevy-example-runner/blob/results/202401211850-0fa14c86de061dee59e3764ebfbaa4ab55a306cf/Windows-percy#L6
