### ISSUE TITLE
make it possible to run on a PR

### ISSUE THREAD

**Issue by mockersf** [TheBevyFlock/bevy-example-runner#2]
It should be possible to run on a PR, to compare with `main`
Results from a PR should either be displayed on their own page, or on the main page but only when asked for to not make the results on main harder to read

**Comment by rparrett** [comment]
Have you considered the sort of setup where you can summon the runner from a PR comment?

**Comment by mockersf** [comment]
The cleanest way to integrate would be to build a GitHub app, with a bot that would react to a webhook. The GitHub app would have permissions to trigger jobs in this repo and to comment on PRs in the Bevy repo, and it would be triggered by the webhook

**Comment by BD103** [comment]
I know it's been a while, but I've been considering hosting a Github App on my Raspberry Pi that can be used with bevy-bencher. Perhaps this can integrate with it? (@bevybot is unused on Github!)

It would require configuring webhooks for the organization that installs it,. and basically all PR comments would be sent to the server, but it would work.

**Comment by BD103** [comment]
Closed by b3c9f581f86156d09748c2a59f054442e99616d6!
